#Vault
spring.application.name=docker
spring.config.import=vault://
spring.cloud.vault.uri=http://10.4.72.9:8200
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.ssl.enabled=false
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.backend-version=2
spring.cloud.vault.kv.default-context=docker

#DB
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = false
spring.jpa.hibernate.use-new-id-generator-mappings= false
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto = none
spring.jpa.open-in-view=false
spring.datasource.hikari.connectionTimeout=40000 
spring.datasource.hikari.idleTimeout=600000 
spring.datasource.hikari.maxLifetime=1200000

#Spring Cloud
spring.cloud.compatibility-verifier.enabled=false


#Servelet
server.tomcat.max-http-post-size=500MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


#External URL's
notify.url = http://10.4.72.9:7014/send/notification
wallet.transaction.log = http://10.4.72.9:7014/api/save-wallet-transaction-log
central.log = http://localhost:8085/SignatureWebService/api/digital/signature/post/saveAgentLogModel/central-log
userprofile.url = http://localhost:44319/api/UserInfo/GetUserProfile
bank.access.token.url = http://localhost:44319/api/Authentication/token
request.uri = https://uaeid-stg.digitaltrusttech.com/credential-exchange/api/verifier/presentation/request/uri
verify.uri = https://uaeid-stg.digitaltrusttech.com/credential-exchange/api/verifier/presentation/verify/result/
verify.vp.token = https://uaeid-stg.digitaltrusttech.com/uaeid-w3c1/api/vc/verifier/presentation/verify/result/vpToken
notification.url = http://10.4.72.9:7014/send/notification
subscriber.ob.data= http://localhost:8081/On-Boarding/api/post/fetch/subscriber-ob-data
verify.face = http://10.4.72.23:8083/verify_images
create.request=https://uaeid-stg.digitaltrusttech.com/credential-exchange/api/verifier/presentation/request/uri
fetch.verify=https://uaeid-stg.digitaltrusttech.com/credential-exchange/api/verifier/presentation/verify/result_with_vptoken
api.access=https://uaeid-stg.digitaltrusttech.com:4004/api/auth/GetApiAccess
org.name=Tasheel Legal Consultancy LLC
save.doc=https://uaeid-stg.digitaltrusttech.com:4004/api/documents/savenewdoc
doc.status=https://uaeid-stg.digitaltrusttech.com:4004/api/documents/
edms.url=https://uaeid-stg.digitaltrusttech.com:4004/api/downloaddoc/
pdf.embed=http://localhost:6906/PdfEmbedding/api/poa/modify-pdf
notification=http://localhost:8081/SpringBootPushNotification/send/notification
file.sign.url = http://localhost:8085/SignatureWebService/api/digital/signature/post/sign/icp
portal.url = https://uaeid-stg.digitaltrusttech.com/icp-simulations


#Configurtaions
poa.Coordinates = { "principalName": "85,600", "agentName": "80,585", "scope": "190,390", "startDate": "173,318", "endDate": "200,252" }
base64.pdf = ""
org.id=65dfb43a-2693-48dc-983c-7a9845f38661
scope.list=Money Transfer,Bank Account Opening,Sell A Car
sign.x-coordinate = 420
sign.y-coordinate = 630
pdf.file.path=/home/UAEID/java-services/uaedigitalidgatewaysimulations/
pdf.file.name=document.pdf
project.name = UAEID
title.for.claims.pid = UAEID ID
title.for.claims.mdl = MDL
attribute.name.pid =UAEIDCredential
attribute.name.mdl = mDL
bank.client.id = Ba8N0XWd3Bf9VqRvHCVn7NpCuwffKxJI23jXLq0BTzpt33Tq
bank.secret =AGcpJeUeqhgfgPTTeR03LRTdq2rOWr4skQVAS6XqylTE1Dck8jJaFgpIPIdF9RoD
exchange.rate = 3.673
exchange.currency = AED


#Kafka
spring.kafka.bootstrap-servers=10.4.72.9:9096,10.4.72.9:9097,10.4.72.9:9098
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=log-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.properties.security.protocol=PLAINTEXT
kafka.topic.log=central-log-topic




