package com.dtt.simulations.enums;

public enum ServiceNames {

	SERVICE_PROVIDER_ONBOARDED
	, SUBSCRIBER_ONBOARDED     
	, CERTIFICATE_PAIR_ISSUED  
	, SUBSCRIBER_AUTHENTICATED 
	, DIGITALLY_SIGNED         
	, KEY_PAIR_GENERATED       
	, CSR_CREATED              
	, CERTIFICATE_GENERATED    
	, PKI_AUTHENTICATED        
	, SIGNATURE_VERIFIED       
	, OTHER
	,REGISTRATION_OTP_SENT
	,SUBSCRIBER_REGISTRATION
	, HOTEL
	, BANK
	, RENT_CAR
	, EXCHANGE_MONEY
	, INSURANCE_HEALTH
	, SCHOOL_ADMISSION
	,SIM

}
